### ISSUE TITLE
Do you need help getting this to go faster?

### ISSUE THREAD

**Issue by matthewdeanmartin** [romanin-rf/rsv#1]
100% chance this would be 20 or 200x faster if compiled with mypyc.

Here is an example of how I did it on another project: https://github.com/matthewdeanmartin/untruncate_json

let me know so I can put together an PR

**Comment by peachboy0** [comment]
To be honest, I don't mind, but I didn't understand it. I am not a very experienced programmer...

The only thing I've done now is look into the [mypyc documentation](https://mypyc.readthedocs.io/en/stable/using_type_annotations.html).

In principle, it makes sense.

PS: This time, I will try to answer faster...
